// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufmmtcnvljuigopzgtje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmbW10Y252bGp1aWdvcHpndGplIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyOTQzMDEsImV4cCI6MjA2MTg3MDMwMX0.7PmJBmX4rPiXAcE5p7zEAqqXZCAtDM7DcwBWb-PReN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);